apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: deployment-workflow-template
spec:
  entrypoint: main
  arguments:
    parameters:
      - name: ENV
        value: "dev"  # Default environment
      - name: IMAGE_TAG
        value: ""  # Default value for image tag
      - name: CUSTOM_TEXT
        value: ""  # Default value for custom text
  templates:
    - name: main
      steps:
        - - name: git-checkout
            template: git-checkout
        # - - name: modify-configuration
        #     template: modify-configuration
        #     arguments:
        #       parameters:
        #         - name: IMAGE_TAG
        #           value: "{{workflow.parameters.IMAGE_TAG}}"
        #         - name: CUSTOM_TEXT
        #           value: "{{workflow.parameters.CUSTOM_TEXT}}"
        # - - name: check-configuration
        #     template: check-configuration
        # - - name: git-commit-push
        #     template: git-commit-push
        #     arguments:
        #       parameters:
        #         - name: IMAGE_TAG
        #           value: "{{workflow.parameters.IMAGE_TAG}}"


  templates:
    - name: git-checkout
      container:
        image: alpine/git
        command: [sh, -c]
        args: 
          - |
            git clone --branch release-1.1 https://github.com/theadityab/argo-testing.git \
            ls -l 

    # - name: modify-configuration
    #   inputs:
    #     parameters:
    #       - name: IMAGE_TAG
    #       - name: CUSTOM_TEXT
    #   container:
    #     image: alpine
    #     command: [sh, -c]
    #     args: |
    #       sed -i 's/tag: "[^"]*"/tag: "{{inputs.parameters.IMAGE_TAG}}"/' application_set.yaml
    #       sed -i 's/homepageText: "[^"]*"/homepageText: "{{inputs.parameters.CUSTOM_TEXT}}"/' application_set.yaml

    # - name: check-configuration
    #   container:
    #     image: alpine/git
    #     command: [sh, -c]
    #     args: ["/usr/bin/git diff"]

    # - name: git-commit-push
    #   inputs:
    #     parameters:
    #       - name: IMAGE_TAG
    #   container:
    #     image: alpine/git
    #     command: [sh, -c]
    #     args: |
    #       git add . && \
    #       git commit -m "Updated with {{inputs.parameters.IMAGE_TAG}}" && \
    #       git push --set-upstream origin master

